### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by jhamman** [whoisryosuke/next-mdx-deck#2]
Hi @whoisryosuke - just took a look at this repo and would love to take it for a spin. Would it be possible to get a license added to the repo? Thanks!

**Comment by whoisryosuke** [comment]
Oh funny, I didn't notice it was missing one 😅 Tossed one up in the latest master branch. Thanks for catching that 👍

**Comment by jhamman** [comment]
Thanks @whoisryosuke!
